### ISSUE TITLE
generator failes duo to update in HashMap api

### ISSUE THREAD

**Issue by HesamR** [Snektron/vulkan-zig#2]
zig: master branch
os: win

out: 
```
.\deps\vulkan-zig\generator\vulkan\generator.zig:32:34: error: no member named 'items' in struct 'std.hash_map.HashMap([]const u8,std.array_list.ArrayListAlignedUnmanaged(std.special.deps.vulkan-zig.generator.vulkan.registry.Field,null),std.hash_map.hashString,std.hash_map.eqlString,80)'
        for (self.enum_extensions.items()) |*entry| {
                                 ^
```

**Comment by Snektron** [comment]
This was caused by a recent change in the HashMap api (A new implementation was made and the old one was renamed). Unfortunately, the new implementation crashes somewhere, so i've just taken the old implementation for now. 

I should probably set up some CI stuff for this, also for vk.xml. Thanks for reporting!
