### ISSUE TITLE
StructureType.physical_device_vulkan_1_X_Y does not generate properly

### ISSUE THREAD

**Issue by AODQ** [Snektron/vulkan-zig#3]
The `_` between `1` and `X` gets omitted when generated for assignments in struct fields. For example, for `PhysicalDeviceVulkan11Features`, `sType` is set to `.physical_device_vulkan_11_features` instead of the correct behavior `.physical_device_vulkan_1_1_features`.

**Comment by Snektron** [comment]
I was generating the `sType` from the struct's name, which failed for PhysicalDeviceVulkan11Features as the SegmentIterator splits that up into `Physical Device Vulkan 11 Features` instead of `Physical Device Vulkan 1 1 Features`. It turns out vk.xml actually encodes this information in the `values` field on the sType member, so the structure type is now parsed and rendered from there.
