### ISSUE TITLE
Alternate naming convention

### ISSUE THREAD

**Issue by kuon** [Snektron/vulkan-zig#51]
In my project, the naming convention for function is lower case snake case, like this:

```
foo.do_something()
```

I realize this is not zig standard style, but this is the style we enforce in our code.

I was wondering if it was possible (and easy) to add a flag to the generator to change the naming style of the function generated).

Or maybe the most flexible thing would be to have a hook mechanism called on generation:

```
    const hooks = struct {
      pub fn fname(const vk_name: []u8, const new_name: []u8) {
         // here rewrite name
      }
    } 
    const gen = vkgen.VkGenerateStep.init(b, "libs/vk.xml", "vk.zig", hooks);

```

If you think that could be included in the library, I'll happily make a PR.

**Comment by Snektron** [comment]
The project already contains functionality to rewrite names, so this could be implemented through some sort of configuration structure. 

The main question is whether this is a good idea with regards to the Zig library ecosystem, because this could result in every library using a slightly different style, and so resulting in a bunch of incompatible projects. I realize that right now there aren't many libraries that depend on vulkan-zig, but even so Im still quite reluctant to such options for this reason.

**Comment by kuon** [comment]
As I said here: https://github.com/ziglang/zig/issues/1097 I am using snake_case for function because camelCase is awful to read for me, it tires me an slow me when reading code. But there is no consensus on this. And I don't want to impose anything.

I agree it is not ideal to have different naming convention, but I think many enterprises have naming convention developers just have to stick with. And I already saw `.h` full of `#define` just to change the case of a library.

I don't want to overstep, if you feel it's not to be integrated in the project, it's ok.

**Comment by Snektron** [comment]
Changing the code to snake case should be relatively easy, though I'm reluctant to make it a configuration option. I suggest to fork the project and adapt the rendering commands to snake case where required.

This may be visited again if/when the Zig "recommended" style switches to :snake: case
