### ISSUE TITLE
Use slices instead of u32 lengths and pointers?

### ISSUE THREAD

**Issue by CodesOtakuYT** [Snektron/vulkan-zig#91]
Are there any plans in the future to support this? as to improve the safety and the ergonomics of the API just like how ash does it.

**Comment by Snektron** [comment]
There are two aspects to this feature:
- slices in function prototypes
- slices in structs

The former is already done in vulkan-zig and works fine. The latter requires re-writing structs, and while the general performance overhead of that would probably be not too bad (though youd be copying a bunch of bytes every time and probably better to avoid that), the real problem is for pNext chains. That either requires dynamic allocation or figuring out the max required static size by allocating all possible extension chains on the stack. It is possible for sure, but originally I decided against it because of the points above. Note that a wrapper type is not possible here due to abi layout constraints.

**Comment by CodesOtakuYT** [comment]
Do you have any idea on how rust binding ash manages that?

**Comment by ashpil** [comment]
That wouldn't be a fully general solution, though, as sometimes two fields are specified by one length, or a length is nested somewhere in another struct rather than being adjacent to the field.

**Comment by InKryption** [comment]
What if we just also generated methods named after the ptr + length pair, which returns a slice?

**Comment by CodesOtakuYT** [comment]
> That wouldn't be a fully general solution, though, as sometimes two fields are specified by one length, or a length is nested somewhere in another struct rather than being adjacent to the field.

most of the related ptr/len pairs have the same name, if we strip out the prefix and the suffix. for the other edge cases, we can either leave them unchanged or we can manually work around those.

**Comment by Snektron** [comment]
> What if we just also generated methods named after the ptr + length pair, which returns a slice?

That would work, but how often do you read from a parameter struct?

> Maybe instead of using zig's built in pointers (and therefore having to copy to convert) there could be a wrapper struct of some kind ie.

Im not sure that this will abi compatible.

> Do you have any idea on how rust binding ash manages that?

It doesnt. Ash uses builders to construct a struct and perform the conversion but id like to avoid that. See for example [InstanceCreateInfoBuilder#enabled_layer_names](https://docs.rs/ash/latest/ash/vk/struct.InstanceCreateInfoBuilder.html#method.enabled_layer_names).

**Comment by Snektron** [comment]
This has been quiet for a while. I'm gonna make the decision to not do this for now, to avoid rewriting the struct.
